search_for_public_info_task:
  description: >
    Search online for public data about: {customer_name_or_business}.

    Focus on:
    - Company website
    - LinkedIn
    - Business directories
    - News or press releases

    Return results using this exact JSON format:
    {
      "results": [
        {
          "url": "https://example.com",
          "source": "LinkedIn",
          "summary": "Marketing Director profile. Contact email listed."
        },
        {
          "url": "https://example.org",
          "source": "Company Site",
          "summary": "Company provides logistics software. Location: Chicago."
        }
      ]
    }
  expected_output: >
    JSON list of URLs and summaries. No extra text.
  agent: lead_generation_agent

extract_key_details_task:
  description: >
    Based on search results for {customer_name_or_business}, extract the following fields:

    {
      "company_name": "",
      "contact_name": "",
      "email": "",
      "industry": "",
      "company_size": "",
      "location": ""
    }

    Use "null" if any field is missing. Output only the JSON.
  expected_output: >
    A structured JSON object with 6 fields. No explanation or extra content.
  agent: lead_generation_agent

evaluate_lead_potential_task:
  description: >
    Evaluate the lead quality for {customer_name_or_business} based on the extracted details.

    Use the target industry: "{target_industry}"

    Return the evaluation in this JSON format:
    {
      "score": 0,
      "fit": "low" | "medium" | "high",
      "notes": ""
    }

    Scoring:
    - Start at 100
    - -20 if no email
    - -15 if company size is missing
    - -20 if industry does not match target industry

    Only return JSON. Do not explain the logic.
  expected_output: >
    JSON lead evaluation. Must match the exact format given.
  agent: lead_generation_agent

summarize_findings_task:
  description: >
    Use the extracted info and lead evaluation for {customer_name_or_business} to create a structured summary.

    Use this bullet format:
    - Company: <company_name>
    - Contact: <contact_name> (<email>)
    - Industry: <industry>
    - Size: <company_size>
    - Location: <location>
    - Fit Score: <score> (<fit>)
    - Notes: <notes>

    Return only the formatted bullet list.
  expected_output: >
    Bullet-point summary. No extra words or introduction.
  agent: lead_generation_agent